-----Display all patients-----
SELECT * FROM Patients;

-----Display all doctors-----
SELECT * FROM Doctors;

-----Display all departments-----
SELECT * FROM Departments;

-----Display all appointments-----
SELECT * FROM Appointments;

-----Display all treatments-----
SELECT * FROM Treatments;

-----Display all bills-----
SELECT * FROM Bills;

-----Display all medicines-----
SELECT * FROM Medicines;

-----Display all prescriptions-----
SELECT * FROM Prescriptions;

-----Count total patients-----
SELECT COUNT(*) AS total_patients 
FROM Patients;

-----Count total doctors-----
SELECT COUNT(*) AS total_doctors 
FROM Doctors;

-----Count total appointments-----
SELECT COUNT(*) AS total_appointments 
FROM Appointments;

-----Count total bills-----
SELECT COUNT(*) AS total_bills 
FROM Bills;

-----Count appointments by doctor-----
SELECT doctor_id, COUNT(*) AS total_appointments
FROM Appointments
GROUP BY doctor_id;

-----Count patients by gender-----
SELECT gender, COUNT(*) AS total_patients
FROM Patients
GROUP BY gender;

-----Total hospital revenue-----
SELECT SUM(total_amount) AS total_revenue
FROM Bills;

-----Average bill amount-----
SELECT AVG(total_amount) AS average_bill
FROM Bills;

-----Highest bill amount-----
SELECT MAX(total_amount) AS highest_bill
FROM Bills;

-----Lowest bill amount-----
SELECT MIN(total_amount) AS lowest_bill
FROM Bills;

-----Average treatment cost-----
SELECT AVG(treatment_cost) AS average_treatment_cost
FROM Treatments;

-----Most expensive treatment-----
SELECT *
FROM Treatments
ORDER BY treatment_cost DESC
LIMIT 1;

-----Top 5 highest bills-----
SELECT *
FROM Bills
ORDER BY total_amount DESC
LIMIT 5;

-----Top 5 expensive treatments-----
SELECT *
FROM Treatments
ORDER BY treatment_cost DESC
LIMIT 5;

-----Patient details with appointment dates-----
SELECT p.first_name, p.last_name, a.appointment_date
FROM Patients p
JOIN Appointments a
ON p.patient_id = a.patient_id;

-----Doctor names with departments-----
SELECT d.first_name, d.last_name, dep.department_name
FROM Doctors d
JOIN Departments dep
ON d.department_id = dep.department_id;

-----Appointment details with patient and doctor-----
SELECT
p.first_name,
p.last_name,
d.first_name AS doctor_first_name,
d.last_name AS doctor_last_name,
a.appointment_date
FROM Appointments a
JOIN Patients p
ON a.patient_id = p.patient_id
JOIN Doctors d
ON a.doctor_id = d.doctor_id;

-----Bills with patient names-----
SELECT
p.first_name,
p.last_name,
b.total_amount,
b.payment_status
FROM Bills b
JOIN Patients p
ON b.patient_id = p.patient_id;

-----Treatment details with patient names-----
SELECT
p.first_name,
p.last_name,
t.diagnosis,
t.treatment_cost
FROM Treatments t
JOIN Appointments a
ON t.appointment_id = a.appointment_id
JOIN Patients p
ON a.patient_id = p.patient_id;

-----Revenue by payment status-----
SELECT payment_status,
SUM(total_amount) AS revenue
FROM Bills
GROUP BY payment_status;

-----Monthly revenue-----
SELECT
EXTRACT(MONTH FROM bill_date) AS month,
SUM(total_amount) AS revenue
FROM Bills
GROUP BY month
ORDER BY month;

-----Doctors by specialization-----
SELECT specialization,
COUNT(*) AS total_doctors
FROM Doctors
GROUP BY specialization;

-----Medicines above average price-----
SELECT *
FROM Medicines
WHERE price > (
SELECT AVG(price)
FROM Medicines
);

-----Patients with more than one appointment-----
SELECT patient_id,
COUNT(*) AS visits
FROM Appointments
GROUP BY patient_id
HAVING COUNT(*) > 1;

-----Doctors with more than 5 appointments-----
SELECT doctor_id,
COUNT(*) AS total_appointments
FROM Appointments;
GROUP BY doctor_id
HAVING COUNT(*) > 5;
SELECT * FROM Appointments;

-----Top 5 busiest doctors-----
SELECT
d.doctor_id,
d.first_name,
d.last_name,
COUNT(a.appointment_id) AS total_appointments
FROM Doctors d
JOIN Appointments a
ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id, d.first_name, d.last_name
ORDER BY total_appointments DESC
LIMIT 5;

-----Top 5 patients by total spending-----
SELECT
p.patient_id,
p.first_name,
p.last_name,
SUM(b.total_amount) AS total_spent
FROM Patients p
JOIN Bills b
ON p.patient_id = b.patient_id
GROUP BY p.patient_id, p.first_name, p.last_name
ORDER BY total_spent DESC
LIMIT 5;

-----Revenue generated by each doctor-----
SELECT
d.doctor_id,
d.first_name,
d.last_name,
SUM(b.total_amount) AS revenue
FROM Doctors d
JOIN Appointments a
ON d.doctor_id = a.doctor_id
JOIN Bills b
ON a.patient_id = b.patient_id
GROUP BY d.doctor_id, d.first_name, d.last_name
ORDER BY revenue DESC;

-----Rank bills by amount-----
SELECT
bill_id,
total_amount,
RANK() OVER (ORDER BY total_amount DESC) AS bill_rank
FROM Bills;

-----Running total revenue-----
SELECT
bill_date,
total_amount,
SUM(total_amount) OVER (ORDER BY bill_date) AS running_total
FROM Bills;

-----Most prescribed medicine-----
SELECT
medicine_id,
COUNT(*) AS times_prescribed
FROM Prescriptions
GROUP BY medicine_id
ORDER BY times_prescribed DESC
LIMIT 1;

-----Patients with pending bills-----
SELECT
p.patient_id,
p.first_name,
p.last_name,
b.total_amount
FROM Patients p
JOIN Bills b
ON p.patient_id = b.patient_id
WHERE b.payment_status = 'Pending';
SELECT * FROM Patients;
-----Appointments by status-----
SELECT
status,
COUNT(*) AS total
FROM Appointments
GROUP BY status;